version: "3.5"

services:
  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - frontend-node_modules:/usr/src/app/node_modules

volumes:
  frontend-node_modules:
